### ISSUE TITLE
MyPackage 'is not in the npm registry.'

### ISSUE THREAD

**Issue by brenwell** [drone-plugins/drone-npm#34]
Hey there, thanks for the lib!

I was hoping you could help me diagnose my issue publishing. It says its not an npm registry but it exists and I have publish 12 versions there. Any ideas??

https://www.npmjs.com/package/each-after

Cheers

```bash
+ npm --version
time="2018-03-10T12:21:41Z" level=info msg="Specified credentials" email="$NPM_EMAIL" username="$NPM_USERNAME" 
time="2018-03-10T12:21:41Z" level=info msg="Writing npmrc" path="/root/.npmrc" 
3.10.10
+ npm config set always-auth true
+ npm whoami
$NPM_USERNAME
time="2018-03-10T12:21:44Z" level=info msg="No registry specified in the package.json" 
time="2018-03-10T12:21:44Z" level=info msg="Found package.json" name=each-after version=1.0.12 
+ npm view each-after versions --json
time="2018-03-10T12:21:45Z" level=info msg="Version not found in the registry" 
time="2018-03-10T12:21:45Z" level=info msg="Publishing package" 
+ npm publish
npm ERR! publish Failed PUT 404
npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "publish"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not Found : each-after
npm ERR! 404 
npm ERR! 404  'each-after' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /drone/src/github.com/brenwell/each-after/npm-debug.log
exit status 1
```

**.drone.yml**

```yaml
---
pipeline:
  build:
    image: node:8
    commands:
      - npm install
      - npm build
      - npm test

  npm:
    image: plugins/npm
    username: $NPM_USERNAME
    password: $NPM_PASSWORD
    email: $NPM_EMAIL
```

**docker-compose.yml**

```yaml

version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 8822:8000
      - 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      ...
      - NPM_USERNAME=brenwell
      - NPM_PASSWORD=somepassword
      - NPM_EMAIL=my@email.com

```

**package.json**

```json
{
  "name": "each-after",
  "version": "1.0.12",
  "description": "Iterate through an array with an interval between each call. Stop & kill iteration.",
  "main": "lib/each-after.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "start": "npm run build && npm test",
    "lib": "npm run build && npm run min",
    "build": "babel index.js -o ./lib/each-after.js -s inline",
    "min": "minify index.js -o ./lib/each-after.min.js",
    "test": "npm run unit && npm run lint",
    "unit": "mocha",
    "lint": "eslint index.js --fix",
    "prepublishOnly": "npm run lib && npm test"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/brenwell/each-after.git"
  },
  "keywords": [
    "iteration",
    "loop",
    "array",
    "delay",
    "stop",
    "kill"
  ],
  "author": "Brendon Blackwell",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/brenwell/each-after/issues"
  },
  "homepage": "https://github.com/brenwell/each-after#readme",
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.35",
    "@babel/core": "^7.0.0-beta.35",
    "@babel/preset-env": "^7.0.0-beta.35",
    "babel-minify": "^0.2.0",
    "chai": "^4.1.2",
    "eslint": "^4.13.1",
    "mocha": "^4.0.1",
    "sinon": "^4.1.3"
  }
}


```
