### ISSUE TITLE
Plugin is broken due to npm's new authToken requirements

### ISSUE THREAD

**Issue by dessalines** [drone-plugins/drone-npm#58]
As of a few months ago, npm starting requiring auth tokens rather than logins, to be able to publish there, which broke this plugin. Took me a while to figure out a simple solution, but here it is for anyone who finds it useful:

```yml
  - name: npm publish
    image: node:17-alpine
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
      - echo "email = $NPM_EMAIL" >> ~/.npmrc
      - npm publish
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_token
      NPM_EMAIL: MY_EMAIL
    when:
      ref:
        - refs/tags/*
```
